var DISQUS=function(b){var e=b.DISQUS||{};e.AssertionError=function(a){this.message=a};e.AssertionError.prototype.toString=function(){return"Assertion Error: "+(this.message||"[no message]")};e.assert=function(a,j,h){if(!a)if(h)b.console&&b.console.log("DISQUS assertion failed: "+j);else throw new e.AssertionError(j);};var a=[];e.define=function(i,j){typeof i==="function"&&(j=i,i="");for(var h=i.split("."),f=h.shift(),d=e,g=(j||function(){return{}}).call({overwrites:function(a){a.__overwrites__=!0;
return a}},b);f;)d=d[f]?d[f]:d[f]={},f=h.shift();for(var o in g)g.hasOwnProperty(o)&&(!g.__overwrites__&&d[o]!==null&&e.assert(!d.hasOwnProperty(o),"Unsafe attempt to redefine existing module: "+o,!0),d[o]=g[o],a.push(function(a,f){return function(){delete a[f]}}(d,o)));return d};e.use=function(a){return e.define(a)};e.cleanup=function(){for(var b=0;b<a.length;b++)a[b]()};return e}(window);
DISQUS.define(function(b,e){var a=b.DISQUS,i=b.document,j=i.getElementsByTagName("head")[0]||i.body,h={running:!1,timer:null,queue:[]};a.defer=function(a,d){function g(){var a=h.queue;if(a.length===0)h.running=!1,clearInterval(h.timer);for(var f=0,d;d=a[f];f++)d[0]()&&(a.splice(f--,1),d[1]())}h.queue.push([a,d]);g();if(!h.running)h.running=!0,h.timer=setInterval(g,100)};a.each=function(a,d){var g=a.length,b=Array.prototype.forEach;if(isNaN(g))for(var e in a)a.hasOwnProperty(e)&&d(a[e],e,a);else if(b)b.call(a,
d);else for(b=0;b<g;b++)d(a[b],b,a)};a.extend=function(f){a.each(Array.prototype.slice.call(arguments,1),function(a){for(var g in a)f[g]=a[g]});return f};a.serializeArgs=function(f){var d=[];a.each(f,function(a,f){a!==e&&d.push(f+(a!==null?"="+encodeURIComponent(a):""))});return d.join("&")};a.isString=function(a){return Object.prototype.toString.call(a)==="[object String]"};a.serialize=function(f,d,g){d&&(f+=~f.indexOf("?")?f.charAt(f.length-1)=="&"?"":"&":"?",f+=a.serializeArgs(d));if(g)return d=
{},d[(new Date).getTime()]=null,a.serialize(f,d);d=f.length;return f.charAt(d-1)=="&"?f.slice(0,d-1):f};a.require=function(f,d,g,b,e){function h(c){if(c.type=="load"||/^(complete|loaded)$/.test(c.target.readyState))b&&b(),l&&clearTimeout(l),a.bean.remove(c.target,s,h)}var m=i.createElement("script"),s=m.addEventListener?"load":"readystatechange",l=null;m.src=a.serialize(f,d,g);m.async=!0;m.charset="UTF-8";(b||e)&&a.bean.add(m,s,h);e&&(l=setTimeout(function(){e()},2E4));j.appendChild(m);return a};
a.requireStylesheet=function(f,d,g){var b=i.createElement("link");b.rel="stylesheet";b.type="text/css";b.href=a.serialize(f,d,g);j.appendChild(b);return a};a.requireSet=function(f,d,b){var e=f.length;a.each(f,function(f){a.require(f,{},d,function(){--e===0&&b()})})};a.injectCss=function(a){var d=i.createElement("style");d.setAttribute("type","text/css");a=a.replace(/\}/g,"}\n");b.location.href.match(/^https/)&&(a=a.replace(/http:\/\//g,"https://"));d.styleSheet?d.styleSheet.cssText=a:d.appendChild(i.createTextNode(a));
j.appendChild(d)}});
DISQUS.define(function(b,e){var a=b.DISQUS,i=b.document,j=0,h={"0.0":{},"1.0":{}};if(!a.status)a.config={},a.blocks={theme:{},defaults:{}},a.status=null,a.settings={store_:{},schema_:{"disqus.version":{type:"str"},"disqus.domain":{type:"str"},"disqus.debug":{type:"bool"},"disqus.minified":{type:"bool"},"disqus.readonly":{type:"bool"},"disqus.recaptcha.key":{type:"str"},"disqus.facebook.appId":{type:"str"},"disqus.facebook.apiKey":{type:"str"},"disqus.urls.main":{type:"str"},"disqus.urls.media":{type:"str"},"disqus.urls.sslMedia":{type:"str"},
"disqus.urls.realtime":{type:"str"},"disqus.urls.uploads":{type:"str"},"disqus.urls.unmerged":{type:"str"}}},a.settings.store_={"disqus.recaptcha.key":"6LdKMrwSAAAAAPPLVhQE9LPRW4LUSZb810_iaa8u","disqus.urls.media":"http://mediacdn.disqus.com/1358550049","disqus.urls.main":"http://disqus.com","disqus.urls.uploads":"http://media.disqus.com/uploads","disqus.urls.realtime":"http://rt.disqus.com/forums/realtime-cached.js","disqus.urls.unmerged":"http://disqus.com/embed/profile/unmerged_profiles/","disqus.urls.sslMedia":"https://securecdn.disqus.com/1358550049",
"disqus.domain":"disqus.com","disqus.version":"1358550049","disqus.debug":!1,"disqus.minified":!0},a.settings.add=function(f,d,b){a.assert(a.settings.schema_[f]==null||b,"Unsafe attempt to update settings schema.");a.assert(d.type!=null,"Missing required property 'key'.");a.settings.schema_[f]=d;return a.settings},a.settings.get=function(f,d){var b=a.settings.schema_[f];a.assert(b!=null,"Undefined key '"+f+"'.");var e=a.settings.store_[f];if(e==null)return d;if(b.values&&!b.values.length){var h={};
a.each(b.values,function(a,f){h[a]=f});return h[e]}return e},a.settings.set=function(f,d){var b=a.settings.schema_[f],e;a.assert(b!=null,"Undefined key '"+f+"'.");e=function(a){for(var f=0,b;b=a[f];f++){if(b=="str"&&typeof d=="string")return!0;if(b=="bool"&&typeof d=="boolean")return!0;if(b=="int"&&typeof d=="number")return!0;if(b=="obj"&&typeof d=="object")return!0}return!1}(typeof b.type=="string"?[b.type]:b.type);a.assert(e,"Invalid type for rule '"+f+"'.");b.values&&a.assert(a.contains(b.values,
d),"Value is not acceptable.");b.rule&&a.assert(b.rule(d,f),"Value didn't pass schema's rule.");a.settings.store_[f]=b.values&&!b.values.length?b.values[d]:d},a.isBrowser=function(a){var d=b.navigator.userAgent,g=/(iPhone|Android|iPod|iPad|webOS|Mobile Safari|Windows Phone)/i;switch(a){case "ie":return/msie/i.test(d)&&!/opera/i.test(d);case "ie6":return!b.XMLHttpRequest;case "ie7":return/msie/i.test(d)&&!/opera/i.test(d)&&parseInt(/MSIE\s(\d+\.\d+)/.exec(d)[1],10)==7;case "webkit":return~d.indexOf("AppleWebKit/");
case "opera":return!(!b.opera||!b.opera.buildNumber);case "gecko":return~d.indexOf("Gecko/");case "safari":return~d.indexOf("Safari/");case "chrome":return~d.indexOf("Chrome/");case "mobile":return g.test(d);case "quirks":return i.compatMode==="BackCompat";default:return!1}},a.api=function(f,b){var g=a.comm&&a.comm.Default.recover();if(g){if(!b.type)b.type="GET";if(!b.success)b.success=function(){};if(!b.failure)b.failure=function(){};if(!b.data)b.data={};g.api(f,b.data,b.type,b.success,b.failure)}else a.once("loader.onDefaultChannelReady",
function(){a.api(f,b)})},a.each(["bind","once","unbind","unbindAll","trigger"],function(b){a[b]=function(d,g){var e;d&&(d=d.replace(".","_"));switch(b){case "bind":a.bean.add(a,d,g);break;case "once":e=function(){a.unbind(d,e);g.apply(this,arguments)};a.bind(d,e);break;case "unbind":a.bean.remove(a,d,g);break;case "unbindAll":a.bean.remove(a,d);break;case "trigger":a.bean.fire(a,d,[g])}}}),a.contains=function(a,b){if(a.length){for(var g=0,e=a.length;g<e;g++)if(a[g]==b)return!0;return!1}for(g in a)if(a.hasOwnProperty(g)&&
g==b)return!0;return!1},a.empty=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0},a.extend=function(){var b,d;arguments.length<=1?(b=a,d=[arguments[0]||{}]):(b=arguments[0]||{},d=Array.prototype.slice.call(arguments,1));a.each(d,function(d){a.each(d,function(a,d){b[d]=a})});return b},a.getGuid=function(){return j++},a.partial=function(){var a=arguments[0],b=Array.prototype.slice.call(arguments,1);return function(){for(var g=Array.prototype.slice.call(arguments),h=[],j=0,i=b.length;j<
i;j++)h.push(b[j]===e?g.shift():b[j]);for(;g.length>0;)h.push(g.shift());return a.apply(this,h)}},a.sdk=function(b){function d(d){return function(){function g(h){d!=h.name||b!=h.version||(h.func.apply({},e),a.unbind("loader.onSDKMethodReady",g))}var e=Array.prototype.slice.call(arguments);a.bind("loader.onSDKMethodReady",g)}}var g=h[b||"1.0"];a.assert(g!==e,"version is not supported.");if(!a.empty(g))return g;g=a.settings.get("disqus.debug")?"/js/src/sdk/":"/build/system/sdk/";a.require(a.settings.get("disqus.urls.media")+
g+b+".js");return{getThread:d("getThread"),getSession:d("getSession")}},a.sdk.add=function(b,d,g){a.assert(h[d]!==e,"version is not supported.");h[d][b]=g;a.trigger("loader.onSDKMethodReady",{name:b,version:d,func:g})},a.useSSL=function(f){var d,g,e;if(b.location.href.match(/^https/))if(f){d=["disqus_url","realtime_url","uploads_url"];for(e=0;g=d[e];e++)f[g]=f[g].replace(/^http/,"https");f.media_url=f.ssl_media_url}else{d=["disqus.urls.main","disqus.urls.realtime","disqus.urls.uploads"];for(e=0;g=
d[e];e++)a.settings.set(g,a.settings.get(g).replace(/^http/,"https"));a.settings.set("disqus.urls.media",a.settings.get("disqus.urls.sslMedia"))}},a.useSSL(),a.ready=function(b){function d(){var b=a.settings.get("disqus.urls.media"),d=b+"/js/src/embed/custom/",f=b+"/build/system/",e=a.settings.get("disqus.debug"),h=a.settings.get("disqus.urls.media"),j;a.status="loading";e?(j=b+"/styles/dtpl/defaults.css",b=[d+"strings.js",d+"dtpl.js",d+"actions.js",d+"validators.js",d+"utils.js",d+"db.js",d+"nodes.js",
d+"sandbox.js",d+"tooltip.js",d+"comm.js",d+"ui.js",d+"sso.js",d+"compat.js",d+"facebook.js",d+"tracking.js",f+"defaults.js",b+"/js/src/lib/easyxdm.js",b+"/js/src/json.js",b+"/js/src/sdk/1.0.js"],a.config.includeStacktrace&&b.push(h+"/js/src/lib/stacktrace.js")):(j=f+"/defaults.css",b=[f+"disqus.js"]);a.requireStylesheet(j);a.requireSet(b,e,function(){a.status="ready";a.trigger("loader.onFilesReady")})}if(a.status=="ready")b();else a.once("loader.onFilesReady",function(){b()});a.status===null&&d()},
a.addBlocks=function(b,d){if(d)return function(){var b=a.blocks;a.blocks={};d();a.blocks=a.extend(b,{theme:a.blocks})}();var e={Builder:a.strings.Builder,renderBlock:a.renderBlock,each:a.each,extend:a.extend,blocks:a.blocks[b||"defaults"],interpolate:a.strings.interpolate};return function(a){a(e)}},a.renderBlock=function(b,d){var g=b;typeof b==="string"&&(g=a.getBlock(b));if(g===e)throw"Block "+b+" was not found!";return a.sandbox.wrap(b,g,d)},a.getBlock=function(b){return a.blocks.theme[b]||a.blocks.defaults[b]},
a.window={getSize:function(){return typeof b.innerWidth=="number"?[b.innerWidth,b.innerHeight]:i.documentElement?[i.documentElement.clientWidth||i.body.clientWidth,i.documentElement.clientHeight||i.body.clientHeight]:[-1,-1]},getScrollPosition:function(){var a=i.documentElement;return a&&(a.scrollTop||a.scrollWidth)?[a.scrollWidth,a.scrollTop||i.body.scrollTop]:[i.body.scrollWidth,i.body.scrollTop]}}});
(function(b){function e(a){a=a.relatedTarget;if(!a)return a===null;var b;if(b=a!=this)if(b=a.prefix!="xul")if(b=!/document/.test(this.toString())){var c;a:for(a=a.parentNode;a!==null;){if(a==this){c=!0;break a}a=a.parentNode}b=!c}return b}var a=1,i={},j={},h=/over|out/,f=/[^\.]*(?=\..*)\.|.*/,d=/\..*/,g=((b.document||{}).documentElement||{}).addEventListener,o=g?"addEventListener":"attachEvent",w=function(b,c){return b.__uid=c||b.__uid||a++},p=function(a){a=w(a);return i[a]=i[a]||{}},m=g?function(a,
b,c,d){a[d?"addEventListener":"removeEventListener"](b,c,!1)}:function(a,b,c,d,k){k&&d&&(a["_on"+k]=a["_on"+k]||0);a[d?"attachEvent":"detachEvent"]("on"+b,c)},s=function(a,c,d){return function(k){k=q(k||((this.ownerDocument||this.document||this).parentWindow||b).event);return c.apply(a,[k].concat(d))}},l=function(a,b,c,d,k){return function(f){if(d?d.apply(this,arguments):g||f&&f.propertyName=="_on"+c||!f)b.apply(a,Array.prototype.slice.call(arguments,f?0:1).concat(k))}},c=function(a,b,c,k){var e=
b.replace(d,""),h=p(a),h=h[e]||(h[e]={}),i=c,b=w(c,b.replace(f,""));if(h[b])return a;var t=D[e];t&&(c=t.condition?l(a,c,e,t.condition):c,e=t.base||e);c=(t=y[e])?s(a,c,k):l(a,c,e,!1,k);t=g||t;if(e=="unload")var H=c,c=function(){z(a,e,c)&&H()};a[o]&&m(a,t?e:"propertychange",c,!0,!t&&e);h[b]=c;c.__uid=b;c.__originalFn=i;return e=="unload"?a:j[w(a)]=a},z=function(a,c,b){var n;var k,e,h=p(a),j=c.replace(d,"");if(!h||!h[j])return a;n=(c=c.replace(f,""))?c.split("."):[b.__uid],c=n;for(e=c.length;e--;)k=
c[e],b=h[j][k],delete h[j][k],a[o]&&(j=D[j]?D[j].base:j,k=g||y[j],m(a,k?j:"propertychange",b,!1,!k&&j));return a},r=function(a,c,b){return function(d){for(var k=typeof a=="string"?b(a,this):a,e=d.target;e&&e!=this;e=e.parentNode)for(var f=k.length;f--;)if(k[f]==e)return c.apply(e,arguments)}},u=function(a,b,d,k,e){if(typeof b=="object"&&!d)for(var f in b)b.hasOwnProperty(f)&&u(a,f,b[f]);else{f=typeof d=="string";for(var h=(f?d:b).split(" "),d=f?r(b,k,e):d,g=h.length;g--;)c(a,h[g],d,Array.prototype.slice.call(arguments,
f?4:3))}return a},v=function(a,c,b){var k,e,h,g=typeof c=="string",j=g&&c.replace(f,""),i=z,l=p(a);if(g&&/\s/.test(c)){c=c.split(" ");for(h=c.length-1;v(a,c[h])&&h--;);return a}e=g?c.replace(d,""):c;if(!l||g&&!l[e]){if(l&&j)for(k in l)if(l.hasOwnProperty(k))for(h in l[k])l[k].hasOwnProperty(h)&&h===j&&i(a,[k,j].join("."));return a}if(typeof b=="function")i(a,e,b);else if(j)i(a,c);else for(k in i=e?i:v,c=g&&e,e=e?b||l[e]||e:l,e)e.hasOwnProperty(k)&&(i(a,c||k,e[k]),delete e[k]);return a},E=g?function(a,
c,d){evt=document.createEvent(a?"HTMLEvents":"UIEvents");evt[a?"initEvent":"initUIEvent"](c,!0,!0,b,1);d.dispatchEvent(evt)}:function(a,c,b){a?b.fireEvent("on"+c,document.createEventObject()):b["_on"+c]++},B=function(a,c,b){var d=p(c),k;w(a);d=b?d[b]:d;for(k in d)d.hasOwnProperty(k)&&(b?u:B)(a,b||c,b?d[k].__originalFn:k);return a},q=function(a){var c={};if(!a)return c;var b=a.type,d=a.target||a.srcElement;c.preventDefault=q.preventDefault(a);c.stopPropagation=q.stopPropagation(a);c.target=d&&d.nodeType==
3?d.parentNode:d;if(~b.indexOf("key"))c.keyCode=a.which||a.keyCode;else if(/click|mouse|menu/i.test(b)){c.rightClick=a.which==3||a.button==2;c.pos={x:0,y:0};if(a.pageX||a.pageY)c.clientX=a.pageX,c.clientY=a.pageY;else if(a.clientX||a.clientY)c.clientX=a.clientX+document.body.scrollLeft+document.documentElement.scrollLeft,c.clientY=a.clientY+document.body.scrollTop+document.documentElement.scrollTop;h.test(b)&&(c.relatedTarget=a.relatedTarget||a[(b=="mouseover"?"from":"to")+"Element"])}for(var k in a)k in
c||(c[k]=a[k]);return c};q.preventDefault=function(a){return function(){a.preventDefault?a.preventDefault():a.returnValue=!1}};q.stopPropagation=function(a){return function(){a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}};var y={click:1,dblclick:1,mouseup:1,mousedown:1,contextmenu:1,mousewheel:1,DOMMouseScroll:1,mouseover:1,mouseout:1,mousemove:1,selectstart:1,selectend:1,keydown:1,keypress:1,keyup:1,orientationchange:1,touchstart:1,touchmove:1,touchend:1,touchcancel:1,gesturestart:1,gesturechange:1,
gestureend:1,focus:1,blur:1,change:1,reset:1,select:1,submit:1,load:1,unload:1,beforeunload:1,resize:1,move:1,DOMContentLoaded:1,readystatechange:1,error:1,abort:1,scroll:1},D={mouseenter:{base:"mouseover",condition:e},mouseleave:{base:"mouseout",condition:e},mousewheel:{base:/Firefox/.test(navigator.userAgent)?"DOMMouseScroll":"mousewheel"}},C={add:u,remove:v,clone:B,fire:function(a,c,b){var k,e,h=c.split(" ");for(e=h.length;e--;){var c=h[e].replace(d,""),g=y[c],j=h[e].replace(f,""),i=p(a)[c];if(j){j=
j.split(".");for(k=j.length;k--;)i&&i[j[k]]&&i[j[k]].apply(a,[!1].concat(b))}else if(!b&&a[o])E(g,c,a);else for(k in i)i.hasOwnProperty(k)&&i[k].apply(a,[!1].concat(b))}return a}};b.attachEvent&&u(b,"unload",function(){for(var a in j)if(j.hasOwnProperty(a)){var c=v(j[a]).__uid;c&&(delete j[c],delete i[c])}b.CollectGarbage&&CollectGarbage()});var k=b.bean;C.noConflict=function(){b.bean=k;return this};b.bean=C})(this);
(function(b,e){function a(){this.c={}}function i(a){r=[];m=0;for(v=a.length;m<v;m++)r[m]=a[m];return r}function j(a){for(;a=a.previousSibling;)if(a.nodeType==1)break;return a}function h(a,c,b,k,e,f,n,h,g,j,i){var x,l;if(c&&this.tagName.toLowerCase()!==c)return!1;if(b&&(x=b.match(D))&&x[1]!==this.id)return!1;if(b&&(B=b.match(C)))for(m=B.length;m--;)if(a=B[m].slice(1),!(G.g(a)||G.s(a,RegExp("(^|\\s+)"+a+"(\\s+|$)"))).test(this.className))return!1;if(g&&p.pseudos[g]&&!p.pseudos[g](this,i))return!1;if(k&&
!n)for(l in z=this.attributes,z)if(Object.prototype.hasOwnProperty.call(z,l)&&(z[l].name||l)==e)return this;if(k&&!d(f,this.getAttribute(e)||"",n))return!1;return this}function f(a){return L.g(a)||L.s(a,a.replace(H,"\\$1"))}function d(a,c,b){switch(a){case "=":return c==b;case "^=":return c.match(A.g("^="+b)||A.s("^="+b,RegExp("^"+f(b))));case "$=":return c.match(A.g("$="+b)||A.s("$="+b,RegExp(f(b)+"$")));case "*=":return c.match(A.g(b)||A.s(b,RegExp(f(b))));case "~=":return c.match(A.g("~="+b)||
A.s("~="+b,RegExp("(?:^|\\s+)"+f(b)+"(?:\\s+|$)")));case "|=":return c.match(A.g("|="+b)||A.s("|="+b,RegExp("^"+f(b)+"(-|$)")))}return 0}function g(a){var c=[],b=[],d,f=0,n,g,j,i,x,l=M.g(a)||M.s(a,a.split(t)),a=a.match(P),l=l.slice(0);if(!l.length)return c;g=l.pop();i=l.length&&(d=l[l.length-1].match(k))?e.getElementById(d[1]):e;if(!i)return c;x=g.match(K);n=a&&/^[+~]$/.test(a[a.length-1])?function(a){for(;i=i.nextSibling;)i.nodeType==1&&(x[1]?x[1]==i.tagName.toLowerCase():1)&&a.push(i);return a}([]):
i.getElementsByTagName(x[1]||"*");d=0;for(g=n.length;d<g;d++)if(j=h.apply(n[d],x))c[f++]=j;if(!l.length)return c;f=0;g=c.length;for(n=0;f<g;f++){j=c[f];for(d=l.length;d--;)for(;j=Q[a[d]](j,c[f]);)if(E=h.apply(j,l[d].match(K)))break;E&&(b[n++]=c[f])}return b}function o(a,b,d){d=typeof b=="string"?d(b)[0]:b||e;if(a===window||a&&a.nodeType&&(a.nodeType==1||a.nodeType==9))return!b||a!==window&&d&&d.nodeType&&(d.nodeType==1||d.nodeType==9)&&N(a,d)?[a]:[];if(a&&typeof a==="object"&&isFinite(a.length))return i(a);
if(c=a.match(k))return(u=e.getElementById(c[1]))?[u]:[];if(c=a.match(x))return i(d.getElementsByTagName(c[1]));return!1}function w(a){var c=[],b,d;b=0;a:for(;b<a.length;b++){for(d=0;d<c.length;d++)if(c[d]==a[b])continue a;c[c.length]=a[b]}return c}function p(a,b){var d=typeof b=="string"?p(b)[0]:b||e;if(!d||!a)return[];if(c=o(a,b,p))return c;return R(a,d)}var m,s,l,c,z,r,u,v,E,B,q,y=e.documentElement,D=/#([\w\-]+)/,C=/\.[\w\-]+/g,k=/^#([\w\-]+$)/,n=/^\.([\w\-]+)$/,x=/^([\w\-]+)$/,O=/^([\w]+)?\.([\w\-]+)$/,
F=/\s*([\s\+\~>])\s*/g,I=/[\s\>\+\~]/,J=/(?![\s\w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^'"]*\])/,P=RegExp("("+I.source+")"+J.source,"g"),t=RegExp(I.source+J.source),H=/([.*+?\^=!:${}()|\[\]\/\\])/g,K=RegExp(/^([a-z0-9]+)?(?:([\.\#]+[\w\-\.#]+)?)/.source+"("+/\[([\w\-]+)(?:([\|\^\$\*\~]?\=)['"]?([ \w\-\/\?\&\=\:\.\(\)\!,@#%<>\{\}\$\*\^]+)["']?)?\]/.source+")?("+/:([\w\-]+)(\(['"]?(\w+)['"]?\))?/.source+")?"),Q={" ":function(a){return a&&a!==y&&a.parentNode},">":function(a,c){return a&&a.parentNode==c.parentNode&&
a.parentNode},"~":function(a){return a&&a.previousSibling},"+":function(a,c,b,d){if(!a)return!1;b=j(a);d=j(c);return b&&d&&b==d&&b}};a.prototype={g:function(a){return this.c[a]||void 0},s:function(a,c){return this.c[a]=c}};var G=new a,L=new a,A=new a,M=new a,N="compareDocumentPosition"in y?function(a,c){return(c.compareDocumentPosition(a)&16)==16}:"contains"in y?function(a,c){c=c==e||c==window?y:c;return c!==a&&c.contains(a)}:function(a,c){for(;a=a.parentNode;)if(a===c)return 1;return 0},R=e.querySelector&&
e.querySelectorAll?function(a,b){if(b.getElementsByClassName&&(c=a.match(n)))return i(b.getElementsByClassName(c[1]));return i(b.querySelectorAll(a))}:function(a,b){var a=a.replace(F,"$1"),d=[],k,f=[],n;if(c=a.match(O)){q=b.getElementsByTagName(c[1]||"*");r=G.g(c[2])||G.s(c[2],RegExp("(^|\\s+)"+c[2]+"(\\s+|$)"));n=0;l=q.length;for(s=0;n<l;n++)r.test(q[n].className)&&(d[s++]=q[n]);return d}n=0;q=a.split(",");for(l=q.length;n<l;n++)f[n]=g(q[n]);n=0;for(l=f.length;n<l&&(k=f[n]);n++){var h=k;if(b!==e){h=
[];s=0;for(c=k.length;s<c&&(element=k[s]);s++)N(element,b)&&h.push(element)}d=d.concat(h)}return w(d)};p.uniq=w;p.pseudos={};var S=b.qwery;p.noConflict=function(){b.qwery=S;return this};b.qwery=p})(this,document);
(function(){DISQUS.extend({bean:bean.noConflict(),qwery:qwery.noConflict(),throttle:function(b,e,a,i){var j=(new Date).getTime();DISQUS.bean.add(b,e,function(b){var e=(new Date).getTime();e-j>=i&&(j=e,a(b))})},debounce:function(b,e,a,i){function j(b){h&&clearTimeout(h);h=setTimeout(function(){a(b,f)},i)}var h,f;f=function(){DISQUS.bean.remove(b,e,j)};DISQUS.bean.add(b,e,j)}})})();DISQUS.modules={};DISQUS.addJob=DISQUS.defer;DISQUS.getResourceURL=DISQUS.serialize;
DISQUS.lang={contains:DISQUS.contains,forEach:DISQUS.each,extend:DISQUS.extend,trim:function(b){for(var b=b.replace(/^\s\s*/,""),e=/\s/,a=b.length;e.test(b.charAt(--a)););return b.slice(0,a+1)},partial:DISQUS.partial};DISQUS.events={add:DISQUS.bean.add,remove:DISQUS.bean.remove,debounce:DISQUS.debounce};
DISQUS.browser={ie:DISQUS.isBrowser("ie"),ie6:DISQUS.isBrowser("ie6"),ie7:DISQUS.isBrowser("ie7"),webkit:DISQUS.isBrowser("webkit"),opera:DISQUS.isBrowser("opera"),gecko:DISQUS.isBrowser("gecko"),mobile:DISQUS.isBrowser("mobile"),quirks:DISQUS.isBrowser("quirks")};
DISQUS.define("cookies",function(){return{create:function(b,e,a){b=b+"="+e+"; path=/";a.domain&&(b+="; domain=."+a.domain);a.expiresIn&&(e=new Date,e.setTime(e.getTime()+a.expiresIn),b+="; expires="+e.toGMTString());document.cookie=b},read:function(b){b+="=";for(var e=document.cookie.split(";"),a,i=0;i<e.length;i++){for(a=e[i];a.charAt(0)==" ";)a=a.substring(1,a.length);if(a.indexOf(b)===0)return a.substring(b.length,a.length)}return null},erase:function(b,e){var a=new Date;a.setTime(a.getTime()+
-864E5);a=b+"=; path=/;expires="+a.toGMTString();e.domain&&(a+="; domain=."+e.domain);document.cookie=a}}});
DISQUS.define("ga",function(b){var e,a=function(a){e?e(a):b._gaq.push(a)},i={component:1,"package":2,forum:3,version:4,userType:5};return{setCaller:function(a){e=a},setAccount:function(b){a(["_setAccount",b])},setCustomVar:function(b,e){a(["_setCustomVar",i[b],b,e])},trackPageview:function(){a(["_trackPageview"])},trackEvent:function(b,e,f){a(["_trackEvent",e,b,f,1])},setDomainName:function(b){a(["_setDomainName",b])}}});
DISQUS.define("juggler",function(b){var e=(new Date).getTime().toString(10)+Math.floor(Math.random()*1E6).toString(10),a={},i=function(b){a[b]=this;this._emit=null;this.meta={};this.allowedOverwrites=["thread","forum","forum_id"];this.reservedKeys=this.allowedOverwrites.slice().concat(["imp","event","prev_imp"]);this.preloadBuffer=[]};DISQUS.extend(i.prototype,{disable:function(){this._emit=function(){};this.preloadBuffer=[]},copySettings:function(){return DISQUS.extend({},this.settings)},load:function(a){var h=
this;h.settings=a;h.url=a.url;if(a.disable)return void h.disable();if(b.location.protocol==="https:"){if(a.disableSSL)return void h.disable();h.url=h.url.replace("http:","https:")}DISQUS.each(h.allowedOverwrites,function(b){h.meta[b]=a[b]});h.meta.imp=e;h.meta.prev_imp=DISQUS.cookies.read("__jid");DISQUS.cookies.create("__jid",e,{expiresIn:18E5});h._emit=function(a){DISQUS.each(h.meta,function(b,e){a[e]=h.meta[e]});DISQUS.require(h.url,a,!1)};DISQUS.each(h.preloadBuffer,function(a){h._emit(a)})},
emit:function(a,b){b=DISQUS.extend({},b);DISQUS.each(this.reservedKeys,function(a){if(b[a]!=null)throw"Error: cannot overwrite event context '"+a+"'";});b.event=a;this._emit==null?this.preloadBuffer.push(b):this._emit(b)}});return{client:function(b,e){return a[b]||e&&new i(b)},impId:e}});
(function(b){function e(a){return a!=null&&typeof a.source=="string"&&typeof a.styles=="string"}function a(a,b){return a.hasAttribute?a.hasAttribute(b):a.getAttribute(b)!==null}function i(){for(var b=0,c=r.length;b<c;b++)if(a(r[b],"name")&&r[b].getAttribute("name")=="generator"&&a(r[b],"content")&&r[b].getAttribute("content")=="blogger")return!0;b=l.getElementById("Attribution1");if(b!=null&&b.innerHTML.indexOf("http://www.blogger.com")>0)return!0;return!1}function j(){var b;if(i()){b=l.getElementsByTagName("A");
for(var c=0,d=b.length;c<d;c++)if(!a(b[c],"src")&&a(b[c],"name")&&parseInt(b[c].getAttribute("name"),10)&&b[c].innerHTML==="")return b[c].getAttribute("name")}return null}function h(a){var b=0,c=0;if(!a.offsetParent)return[0,0];do b+=a.offsetLeft,c+=a.offsetTop,a=a.offsetParent;while(a);return[b,c]}function f(a){var b=c.window.getScrollPosition()[1],d=b+c.window.getSize()[1];return a>=b&&a<=d}function d(a){if(!(typeof z!="function"&&typeof a!="function")){var b={preData:"loader.onReady",preInit:"loader.onDataReady",
onInit:"loader.onLibraryReady",afterRender:"loader.onTemplateReady",onReady:"thread.onReady",onPaginate:"thread.onPaginate",onNewComment:"comment.onCreate",preReset:"thread.beforeReset"};c.config.callbacks={};c.config.page={};c.each(b,function(a,b){c.config.callbacks[b]=[]});try{(a||z).call(c.config)}catch(d){}c.each(c.config.callbacks,function(a,d){a.length!==0&&c.each(a,function(a){c.bind(b[d],a)})});c.config.callbacks=b}}function g(){var a={url:"thread.url",title:"thread.title",slug:"thread.slug",
category_id:"thread.category",identifier:"thread.identifier",remote_auth_s3:"request.sso.data",author_s3:"thread.author.sig",api_key:"forum.apiKey"};c.each({disqus_domain:"disqus.domain",disqus_category_id:"thread.category",disqus_thread_slug:"thread.slug",disqus_title:"thread.title",disqus_url:"thread.url",disqus_identifier:"thread.identifier",disqus_per_page:"thread.postsPerPage",disqus_require_moderation_s:"thread.moderatePosts",disqus_skip_auth:"thread.skipAuthRequest",disqus_def_email:"thread.defaults.email",
disqus_def_name:"thread.defaults.name",disqus_default_text:"thread.defaults.placeholder",disqus_shortname:"forum.shortname",disqus_facebook_key:"forum.facebook.key",disqus_custom_strings:"ui.translations",disqus_container_id:"ui.container",DsqLocal:"legacy.trackbacks",disqus_remote_auth_s2:"legacy.sso.data",disqus_author_s2:"legacy.thread.author.sig"},function(a,d){b[d]!=null&&c.settings.set(a,b[d])});if(b.disqus_sort!=null)c.settings.store_["thread.sort"]=b.disqus_sort;b.disqus_developer!=null&&
c.settings.set("disqus.developer",!!b.disqus_developer);c.config&&c.config.page&&(c.config.page.remote_auth_s3!=null&&c.settings.set("request.sso.data",c.config.page.remote_auth_s3),c.config.page.api_key!=null&&c.settings.set("forum.apiKey",c.config.page.api_key),c.each(a,function(a,b){c.config.page[b]!=null&&c.settings.set(a,c.config.page[b])}))}function o(){var a=b.location.hash,d=c.settings.get,e=d("legacy.trackbacks",{});c.extend(c.config,{container_id:d("ui.container","disqus_thread"),trackback_url:e.trackback_url||
null,trackbacks:e.trackbacks||null,absorbStyles:!1});c.config.page={url:d("thread.url",b.location.href),title:d("thread.title",""),slug:d("thread.slug"),sort:d("thread.sort",""),per_page:d("thread.postsPerPage",null),category_id:d("thread.category",""),developer:+d("disqus.developer",0),identifier:d("thread.identifier",""),require_mod_s:d("thread.moderatePosts"),remote_auth_s3:d("request.sso.data"),author_s3:d("thread.author.sig"),api_key:d("forum.apiKey"),disqus_version:d("disqus.version"),remote_auth_s2:d("legacy.sso.data"),
author_s2:d("legacy.thread.author.sig")};if(~a.search(/comment\-\d+/))c.config.page.lazy="0";else{var g,e=l.getElementById(c.config.container_id);g=h(e)[1];if(e&&f(g))c.config.page.lazy="0"}if(i())c.config.page.blogger_id=j(),c.config.page.url=c.config.page.url.replace(/\?.*$/,"");if(a&&(a=a.match(/comment\-([0-9]+)/)))c.config.page.anchor_post_id=a[1];var F=b.disqus_callback;typeof F=="function"&&c.bind("thread.onReady",function(){F(b.disqus_callback_params||null)});c.config.custom_strings=d("ui.translations",
{});c.extend(c.config,{domain:d("disqus.domain"),shortname:d("forum.shortname")||c.getShortname(),facebook_key:d("forum.facebook.key",null),def_name:d("thread.defaults.name"),def_email:d("thread.defaults.email"),def_text:d("thread.defaults.placeholder",""),skip_auth:d("thread.skipAuthRequest",!1)});d=c.config.shortname+"."+c.config.domain+"/thread.js";c.config.json_url=b.location.href.match(/^https/)?"https://"+d:"http://"+d}function w(a){return Date.UTC(a.getUTCFullYear(),a.getUTCMonth(),a.getUTCDate(),
a.getUTCHours(),a.getUTCMinutes(),a.getUTCSeconds(),a.getUTCMilliseconds())}function p(){c.bind("thread.onReady",function(){function a(){e&&f(e)&&c.trigger("comments.replyViewed");g&&f(g)&&c.trigger("thread.bottomViewed")}var d=l.getElementById("dsq-reply")||l.getElementById("dsq-new-post"),e=d?c.nodes.getPosition(d)[1]+d.offsetHeight:null,d=l.getElementById("dsq-comments"),g=c.nodes.getPosition(d)[1]+d.offsetHeight;a();c.events.debounce(b,"scroll",a,250);c.resettable=!0;c.trigger("thread.onResetReady")});
c.bind("thread.onReady",function(){var a=c.comm.Default.recover(),d=w(new Date);a.log("load:start",C);a.log("load:length",d-C);try{b.jQuery&&jQuery.ui?a.log("jslib","jqueryui:"+jQuery.ui.version):b.jQuery?a.log("jslib","jquery:"+jQuery().jquery):b.Prototype?a.log("jslib","prototype:"+Prototype.Version):b.dojo?a.log("jslib","dojo:"+dojo.version.toString()):b.MooTools?a.log("jslib","mootools:"+MooTools.version):b.Ext?a.log("jslib","ext:"+Ext.version):b.YUI?a.log("jslib","yui:"+YUI.version):a.log("jslib",
"none")}catch(e){a.log("jslib","error")}a.flushLog(null)});c.bind("loader.onTemplateReady",function(){var a=c.comm.Default.recover(),b=c.jsonData;b.context.switches.sigma&&a.enable(b.context.sigma_chance);a.log("hit",1);b.forum.id&&a.addMeta("info:forum_id",b.forum.id);b.thread.id&&a.addMeta("info:thread_id",b.thread.id);b.request.user_type&&a.addMeta("info:user_type",b.request.user_type);b.request.user_id&&a.addMeta("info:user_id",b.request.user_id)});c.once("thread.bottomViewed",function(){c.comm.Default.recover().log("viewed:comments",
1)});c.once("comments.replyViewed",function(){c.comm.Default.recover().log("viewed:comment_box",1)})}function m(){function a(b,c,d,e,f,g){return'<img width="'+b+'" height="'+c+'" alt="'+e+'" src="data:image/'+d+";base64,"+f+'"'+(g?'style="'+g+'"':"")+"/>"}c.jsonData={ready:!1};var b;c.require(c.config.json_url,c.config.page,!0,null,function(){b.innerHTML='There was a problem loading Disqus. For more information, please visit <a href="http://status.disqus.com">status.disqus.com</a>.'});var d=c.qwery("#dsq-content")[0]||
l.createElement("div");d.id="dsq-content";d.style.display="none";b=c.qwery("#dsq-content-stub")[0]||l.createElement("div");b.id="dsq-content-stub";b.innerHTML=c.browser.ie6?"...":a(71,17,"png","DISQUS",E.join(""))+a(16,11,"gif","...",B.join(""),"margin:0 0 3px 5px");var e=c.qwery("#"+c.config.container_id)[0];e.appendChild(d);e.appendChild(b);p();c.ready(function(){c.initThread(function(){b.style.display="none"})})}function s(a){function d(){c.trigger("loader.onDefaultChannelReady")}var e=l.getElementById("dsq-content"),
f=c.settings.get("disqus.urls.media"),g=f+"/build/system/",h=f+"/build/lang/",i=c.jsonData.forum.template.css,j=c.jsonData.forum.template.url,t=c.jsonData.context.switches,m=c.settings.get("disqus.debug"),o=c.settings.get("disqus.preview");c.trigger("loader.onDataReady");if(c.browser.mobile&&!c.jsonData.forum.mobile_theme_disabled)i=c.jsonData.forum.template.mobile.css,j=c.jsonData.forum.template.mobile.url,c.states.isMobile=!0;else if(o)i=o.styles,j=o.source;!b.disqus_no_style&&i&&c.requireStylesheet(i,
{},m);i=c.jsonData.forum.stylesUrl;if(!c.jsonData.context.switches.static_styles||m)i="http://"+c.config.domain+"/forums/"+c.config.shortname+"/styles.css";c.jsonData.forum.hasCustomStyles&&c.requireStylesheet(i,{u:c.jsonData.forum.lastUpdate});j=[j];t.new_toolbar&&(j.push(g+"/defaults.toolbar.js"),c.requireStylesheet(m?f+"/styles/dtpl/defaults.toolbar.css":g+"/defaults.toolbar.css",{},m));~b.location.search.indexOf("fb_xd_fragment")?c.require("http://connect.facebook.net/en_US/all.js"):(c.config.language?
c.config.language!="en"&&j.push(h+c.config.language+".js"):c.jsonData.forum.language!="en"&&j.push(h+c.jsonData.forum.language+".js"),c.comm.Default.recover()||c.comm.Default.create(d).setApiKey(c.jsonData.forum.apiKey),c.requireSet(j,m,function(){var b=function(){return c.strings.get.apply(this,arguments)};c.config.custom_strings&&c.lang.extend(c.strings.translations,c.config.custom_strings);if(c.config.def_text==="")c.config.def_text=b("Type your comment here.");c.registerActions();c.trigger("loader.onActionsReady");
c.nodes.addClass(e,"clearfix");b=e.parentNode;b.removeChild(e);e.innerHTML=c.renderBlock("thread");b.appendChild(e);c.trigger("loader.onLibraryReady");c.dtpl.actions.fire("thread.initialize");c.trigger("loader.onTemplateReady");c.bean.add(e,"click change",function(a){for(var b=a.target,d;b&&b!=e;){if(d=c.dtpl.getAction(b,a)){a.preventDefault();d();break}b=b.parentNode}});c.nodes.container=c.nodes.get("#dsq-content");e.style.display="block";a();c.config.page.anchor_post_id&&c.nodes.scrollTo("#dsq-comment-"+
c.config.page.anchor_post_id);c.dtpl.actions.fire("thread.ready")}))}var l=b.document,c=b.DISQUS,z=b.disqus_config;c.qwery("head")[0]||c.qwery("#disqus_thread");var r=c.qwery("meta"),u=!1,v=[],E=["iVBORw0KGgoAAAANSUhEUgAAAEcAAAARCAYAAAH4YIFjAAAAGXRFWHRTb2Z0d2FyZQBB","ZG9iZSBJbWFnZVJlYWR5ccllPAAABwdJREFUeNpi/P//PwMhwAIiGBkZGeK6V8JVh9rq","dfrc0ixnEDb+wPD2rAAjMSYBBBBRisDWwKxCthIE/q8Q+A8yhCiTAAIIrCi+ZxVMZSAQ","r19UGs4IMxWd/X8Rw3/GOKDhW43fgzwF1hX7n5EJ2dSp2QFNUKcZwJ31/78CkvPBGkGG","MXidSUTWCxBAxAUAEQAcJzCvIXsDBPwsNBU2nbj+AMpdsFA8PAHsLZj3QC5D9hrIAEtN",
"+RMwAzRkxcB0iK3eQ6iQIRAnoMTE//8CyHwmWHQdv/7QAiZ44/ErMP383acsqNB5iMnP","lsFdsUZ6IU3CCCCA4AYBw8kBJgj06gGkmHJAFgPyQV4ExeQEoNgHJHUBQMoAWRzoerBe","YHgeQOJ/APIvQPkNUP4EuIdADBAGBRMQOABxQcakdSipHZldNGvL2zWHL8kD1d0HieVN","33QYqnc/EAfULNwJVw8KTniQwvjAdPz/SEwKmL1KfC5QjwEQr4e5AyVdA3P4ASCe8O3n","b1whmtib6r3IXlfpATBEFbpWH9ygJSdmBtXrOHPbyZWPXn1AqOZRwDSBS+YHo82SOQwi","ZnYMoS+EGC42nGdYzBiAnKpgGAbeA3ECkjwYQNnzH758///6o5cgofVIagy+/vgFF//y","/ecHJLn1/18AA+/teZBcPZL4eSTxBJg7AAKIaomRmpkeV2IG5UcDpMSsAM2zF4BiG9DU","FaCLQxPwBWCC/QBkg/QqoCVuEN4ASuDIaWc/DIMSItBxH0GCrkaqCVBxWO4BJWBQcK/P",
"mrL+I1S8H0i9h4mjFfX7GTRyIdEuHzIfZtb/Zdw3oGyQnvP/d9pNgRc+MLCwJMxxWk7A","I6Ar+YCWVSLLyYkJzIYlZqC6RGBhbg/lFwDlQHoDgfgALLfhjY8/X9XhpWPs/wWM7ody","MBwDylU8nOzyILYIH3cZslxBgM0cKHM+MOTAGCZnri7XCdS7ASgGLsc/fPlug9cxlrO/","wUvYxYwJwCgLwHAMcrVlqCJ9BVlchJ+7EhRyQPwAyGaAFnhgsOPMzUhQroLVAU76yp/g","Gp/vtQbTr45pwMWOp1oDQ6QQiGEi6+EJGLmah0YJQ6CVtu3ivecKYHIpE9b8BPqcDSna","wHSSu8m3eTvPyAHlzsPkDl25/wXMYAOq+XgtBFwIfn/GwCAOSq8HYCGCsNh8+hvksgYZ","IJchDkjljAKoHAKVJ6ByBbnmA5XESOL1oFIZSc9/cJkC1IukPuH/z/cw8fswdwyqcgYg","wAaVYwYbQEnDSI1LbGABEDcCC1lYS4yhfO42n+fvPm9GKsAZkfJDA7RcwwYmQM1CbpUU",
"ADU3AB3AjxJ7wFwAFGsAqp2A0mBDahww8Gv4Mvrf2AKXWyMzgeHbk3wwh5X/DGPkR1Oo","HlCmn49cGCABkL8SgZn8ANbAQQaV4ZBK6yGwgbDr3G2GNx+/gkqShMTe1V///vsnA/KY","joKECjBwMPQCW0EngOrNQWxbHQWGFA8zBlAj5eztpwwbjl9lyPG1DFOUEAIFDqxJB6ks","oC1ZN2NVsDm7zt4GNUhBgdUPrXwckWtQOJB0VQE2XRF8UQt9hodrIGw+FaDcWVjAwAsh","hsD7kAbPO2Dr78ZEBoZfHxQYHNYbwEogvIGjKSfOiNysBpaEL/acv8MODBhuUX7u00Bh","VVx6DZWlxHcDAxQEDl95AMZQAGqHLlSSFIanAnZWll0/f/8Bs2OcDB+5GavJVyGZtevs","rYdL9p2XQ6rZGcnKI54nZRj2uoMCAVr4K8JkQAKgJsdEYN12AbmYYSGqYGJk/NC8bO91","WHKUFRXgwace6ElDIF4PjHWHc3eeMZy98xSU8mB1mwE0FSQCU8ECZiZGVpi+yw9eLIfV",
"lUyMjIf+/f/Pu/bIlTtIdSX5hauo+RagxxMZfr2fwHB3IT/Dy4MMDI/BzTABaP2aAGzm","gPpN4gQDB1pmgIA+EAfcfvoGXl/mB1hXFuBxCLDs6oc26kBJZiIoxShLCqs9e/tp+vdf","v8ENB08Tdf9FwHKsMtxxTfvK/SGgbHfx3vNyoL2g7DjR30r74vqjV2yA6lXgbnI2WtoH","4yhEfGF4sAISSTcm9wOzDcidoE6lPTBLwRuyDMoJ5+DZagnLJIb/f3mh5edGcKoRs+5n","eHUUUgZxiIrhrK2wFchc7KwMmsByANjiAZUfoGzhCEpJIDlQowOYffqRC2RQS+f1x68H","Nx6/ygcqY9A7RMZAc5LcTS/zcLLZwcwB1evAzs/8pfsvwDu9yOplgRECzF4M8a7Gryw0","5NRB+sDtiC/3HjKcKeaDpgAEADVmNIDlsX4DqFPmCOvvMNxdkAAuX95dQFUPKnv06kEB","mQgNOLpV5QbQpAsrcz4QUC+AVJsgqxcgoNcBqQy5QIIdONUDALcn6c0dtMJ9AAAAAElF",
"TkSuQmCC"],B=["R0lGODlhEAALAPQAAP///z2LqeLt8dvp7u7090GNqz2LqV+fuJ/F1IW2ycrf51aatHWs","waXJ14i4ys3h6FmctUCMqniuw+vz9eHs8fb5+meku+Tu8vT4+cfd5bbT3tbm7PH2+AAA","AAAAAAAAACH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQu","aW5mbwAh+QQJCwAAACwAAAAAEAALAAAFLSAgjmRpnqSgCuLKAq5AEIM4zDVw03ve27if","DgfkEYe04kDIDC5zrtYKRa2WQgAh+QQJCwAAACwAAAAAEAALAAAFJGBhGAVgnqhpHIeR","vsDawqns0qeN5+y967tYLyicBYE7EYkYAgAh+QQJCwAAACwAAAAAEAALAAAFNiAgjoth","LOOIJAkiGgxjpGKiKMkbz7SN6zIawJcDwIK9W/HISxGBzdHTuBNOmcJVCyoUlk7CEAAh",
"+QQJCwAAACwAAAAAEAALAAAFNSAgjqQIRRFUAo3jNGIkSdHqPI8Tz3V55zuaDacDyIQ+","YrBH+hWPzJFzOQQaeavWi7oqnVIhACH5BAkLAAAALAAAAAAQAAsAAAUyICCOZGme1rJY","5kRRk7hI0mJSVUXJtF3iOl7tltsBZsNfUegjAY3I5sgFY55KqdX1GgIAIfkECQsAAAAs","AAAAABAACwAABTcgII5kaZ4kcV2EqLJipmnZhWGXaOOitm2aXQ4g7P2Ct2ER4AMul00k","j5g0Al8tADY2y6C+4FIIACH5BAkLAAAALAAAAAAQAAsAAAUvICCOZGme5ERRk6iy7qpy","HCVStA3gNa/7txxwlwv2isSacYUc+l4tADQGQ1mvpBAAIfkECQsAAAAsAAAAABAACwAA","BS8gII5kaZ7kRFGTqLLuqnIcJVK0DeA1r/u3HHCXC/aKxJpxhRz6Xi0ANAZDWa+kEAA7","AAAAAAAAAAAA"],
q={oldest:1,newest:2,best:3,hot:4,highlighted:5},y=["all","none","anon"];try{c.settings.add("disqus.developer",{type:"bool"}).add("disqus.preview",{type:"obj",rule:e}).add("thread.category",{type:["str","int"]}).add("thread.slug",{type:"str"}).add("thread.title",{type:"str"}).add("thread.url",{type:"str"}).add("thread.identifier",{type:["str","int"]}).add("thread.postsPerPage",{type:["str","int"]}).add("thread.moderatePosts",{type:"str",values:y}).add("thread.skipAuthRequest",{type:"bool"}).add("thread.sort",
{type:"str",values:q}).add("thread.defaults.name",{type:"str"}).add("thread.defaults.email",{type:"str"}).add("thread.defaults.placeholder",{type:"str"}).add("thread.author.sig",{type:"str"}).add("forum.shortname",{type:"str"}).add("forum.apiKey",{type:"str"}).add("forum.facebook.key",{type:"str"}).add("ui.translations",{type:"obj"}).add("ui.container",{type:"str"}).add("request.sso.data",{type:"str"}).add("legacy.trackbacks",{type:"obj"}).add("legacy.thread.author.sig",{type:"str"}).add("legacy.sso.data",
{type:"str"}).add("realtime.host",{type:"str"}).add("realtime.port",{type:"int"})}catch(D){return}var C=w(new Date);c.extend({cache:{postboxBusy:{},buttonsToRestore:[],popupProfileCache:{},popupStatusCache:{},toggledReplies:{},postSharing:{},realtime:{interval:null,ongoing_request:null,prev_script:null,last_checked:null,newPosts:[]}},states:{edit:{},realtime:!1,noThirdPartyCookies:null,useLoginWindow:!1,loginDisabled:!1,metaViewport:function(){for(var a=0,b=r.length;a<b;a++)if(r[a].getAttribute("name")==
"viewport")return!0;return!1}(),isMobile:!1},curPageId:"dsq-comments",frames:{},config:{template:null},jsonData:null,isReady:!1,getShortname:function(){function a(b){var b=b.getAttribute?b.getAttribute("src"):b.src,c=[/https?:\/\/(www\.)?disqus\.com\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.disqus\.com/i,/https?:\/\/(www\.)?dev\.disqus\.org\/forums\/([\w_\-]+)/i,/https?:\/\/(www\.)?([\w_\-]+)\.dev\.disqus\.org/i],d=c.length;if(!b||b.substring(b.length-8)!="embed.js")return null;for(var e=
0;e<d;e++){var f=b.match(c[e]);if(f&&f.length&&f.length==3)return f[2]}return null}for(var b=l.getElementsByTagName("script"),c=b.length-1;c>=0;c--){var d=a(b[c]);if(d!==null)return d}return null},callback:function(a){var b=arguments.length>1?Array.prototype.slice.call(arguments,1):[];c.trigger(a,{args:b})},reset:function(a){v.push(a);c.defer(function(){return c.resettable},function(){var a=c.nodes.get("#"+c.config.container_id),b=v.pop();if(b)v=[],c.comm.reset(!0),c.jsonData=null,c.sandbox.invalidateGlobals(),
c.resettable=!1,c.config.page={},a.innerHTML="",c.trigger("thread.beforeReset"),c.unbindAll(),b.reload&&(d(b.config),g(),o(),m())})},updatePost:function(a,b){var d=c.jsonData.posts[a]||{};if(b)b.id=a,c.jsonData.posts[a]=c.extend(d,b),c.trigger("data.onPostUpdate",{id:a,data:b})},reload:function(a){c.require(c.config.json_url,c.config.page,!0,function(){u=!0;typeof a=="function"&&a()})},redraw:function(a){if(u||a)c.sandbox.invalidateGlobals(),a=c.nodes.get("#dsq-content"),a.innerHTML=c.renderBlock("thread"),
c.frames=[],c.dtpl.actions.fire("thread.initialize"),u=!1},initThread:function(a){function d(a){var c=b.onload;b.onload=typeof b.onload!="function"?a:function(){c&&c();a()}}function e(){var a,d;if(c.isReady){if(g&&clearInterval(g),l.getElementById(c.settings.get("ui.container")),a=l.getElementsByTagName("iframe"),d=l.getElementById("dsq-content"))for(var f=0,h=a.length;f<h;f++)a[f].style.width=d.offsetWidth}else g||(g=b.setInterval(e,500))}var f,g;c.browser.ie&&c.config.frame_theme!=="cnn2"&&d(e);
c.trigger("loader.onReady");f=l.getElementById("dsq-content")||l.createElement("div");f.id="dsq-content";f.style.display="none";l.getElementById(c.config.container_id).appendChild(f);c.container=l.getElementById("dsq-content");try{c.browser.ie6&&l.execCommand("BackgroundImageCache",!1,!0)}catch(h){}c.config.page.lazy="0";var i=c.partial(s,a),j=c.partial(c.require,c.config.json_url,c.config.page,!0,i);if(c.jsonData==null)return void j();c.defer(function(){var a=c.jsonData;return a&&(a.ready||a.lazy)},
function(){if(c.jsonData.ready)return void i();c.once("thread.topViewed",function(){j()})})}});d();g();o();m();(function(){function a(b,e){var g=h(d)[1];if(d&&f(g))return c.ready(function(){c.trigger("thread.topViewed")}),typeof e=="function"?e():!0;return!1}var d=l.getElementById(c.config.container_id);a()||c.events.debounce(b,"scroll",a,250)})()})(window);